export enum ECountryCodeName {
	AX = 'Aland Islands',
	AL = 'Albania',
	DZ = 'Algeria',
	AS = 'American Samoa',
	AD = 'Andorra',
	AO = 'Angola',
	AI = 'Anguilla',
	AG = 'Antigua and Barbuda',
	AR = 'Argentina',
	AM = 'Armenia',
	AW = 'Aruba',
	AU = 'Australia',
	AT = 'Austria',
	AZ = 'Azerbaijan',
	BS = 'Bahamas',
	BH = 'Bahrain',
	BD = 'Bangladesh',
	BB = 'Barbados',
	BY = 'Belarus',
	BZ = 'Belize',
	BJ = 'Benin',
	BM = 'Bermuda',
	BT = 'Bhutan',
	BO = 'Bolivia',
	BA = 'Bosnia and Herzegovina',
	BQ = 'Bonaire, Sint Eustatius and Saba',
	BW = 'Botswana',
	BV = 'Bouvet Island',
	BR = 'Brazil',
	IO = 'British Indian Ocean Territory',
	VG = 'Virgin Islands (British)',
	BN = 'Brunei Darussalam',
	BG = 'Bulgaria',
	BF = 'Burkina Faso',
	BI = 'Burundi',
	KH = 'Cambodia',
	CM = 'Cameroon',
	CA = 'Canada',
	CV = 'Cabo Verde',
	KY = 'Cayman Islands',
	CF = 'Central African Republic',
	TD = 'Chad',
	CL = 'Chile',
	CN = 'China',
	CX = 'Christmas Island',
	CC = 'Cocos (Keeling) Islands',
	CO = 'Colombia',
	KM = 'Comoros',
	CG = 'Congo',
	CD = 'Congo (Democratic Republic of the)',
	CK = 'Cook Islands',
	CR = 'Costa Rica',
	HR = 'Croatia',
	CU = 'Cuba',
	CW = 'Curaçao',
	CY = 'Cyprus',
	CZ = 'Czech Republic',
	DK = 'Denmark',
	DJ = 'Djibouti',
	DM = 'Dominica',
	DO = 'Dominican Republic',
	EC = 'Ecuador',
	EG = 'Egypt',
	SV = 'El Salvador',
	GQ = 'Equatorial Guinea',
	ER = 'Eritrea',
	EE = 'Estonia',
	ET = 'Ethiopia',
	FK = 'Falkland Islands (Malvinas)',
	FO = 'Faroe Islands',
	FJ = 'Fiji',
	FI = 'Finland',
	FR = 'France',
	GF = 'French Guiana',
	PF = 'French Polynesia',
	TF = 'French Southern Territories',
	GA = 'Gabon',
	GM = 'Gambia',
	GE = 'Georgia',
	DE = 'Germany',
	GH = 'Ghana',
	GI = 'Gibraltar',
	GR = 'Greece',
	GL = 'Greenland',
	GD = 'Grenada',
	GP = 'Guadeloupe',
	GU = 'Guam',
	GT = 'Guatemala',
	GG = 'Guernsey',
	GN = 'Guinea',
	GW = 'Guinea-Bissau',
	GY = 'Guyana',
	HT = 'Haiti',
	HM = 'Heard Island and McDonald Islands',
	VA = 'Holy See',
	HK = 'Hong Kong',
	HN = 'Honduras',
	HU = 'Hungary',
	IS = 'Iceland',
	IN = 'India',
	ID = 'Indonesia',
	CI = "Côte d'Ivoire",
	IR = 'Iran',
	IE = 'Ireland',
	IM = 'Isle of Man',
	IL = 'Israel',
	IT = 'Italy',
	JM = 'Jamaica',
	JE = 'Jersey',
	JO = 'Jordan',
	KZ = 'Kazakhstan',
	KE = 'Kenya',
	KI = 'Kiribati',
	KW = 'Kuwait',
	KG = 'Kyrgyzstan',
	LV = 'Latvia',
	LB = 'Lebanon',
	LS = 'Lesotho',
	LR = 'Liberia',
	LY = 'Libya',
	LI = 'Liechtenstein',
	LT = 'Lithuania',
	LU = 'Luxembourg',
	MO = 'Macao',
	MK = 'Macedonia',
	MG = 'Madagascar',
	MW = 'Malawi',
	MY = 'Malaysia',
	MV = 'Maldives',
	ML = 'Mali',
	MT = 'Malta',
	MH = 'Marshall Islands',
	MQ = 'Martinique',
	MR = 'Mauritania',
	MU = 'Mauritius',
	YT = 'Mayotte',
	MX = 'Mexico',
	FM = 'Micronesia',
	MD = 'Moldova',
	MC = 'Monaco',
	MN = 'Mongolia',
	ME = 'Montenegro',
	MS = 'Montserrat',
	MA = 'Morocco',
	MZ = 'Mozambique',
	MM = 'Myanmar',
	NA = 'Namibia',
	NR = 'Nauru',
	NP = 'Nepal',
	NL = 'Netherlands',
	NC = 'New Caledonia',
	NZ = 'New Zealand',
	NI = 'Nicaragua',
	NE = 'Niger',
	NG = 'Nigeria',
	NU = 'Niue',
	NF = 'Norfolk Island',
	KP = 'North Korea',
	MP = 'Northern Mariana Islands',
	NO = 'Norway',
	OM = 'Oman',
	PK = 'Pakistan',
	PW = 'Palau',
	PS = 'Palestine, State of',
	PA = 'Panama',
	PG = 'Papua New Guinea',
	PY = 'Paraguay',
	PE = 'Peru',
	PH = 'Philippines',
	PN = 'Pitcairn',
	PL = 'Poland',
	PT = 'Portugal',
	PR = 'Puerto Rico',
	QA = 'Qatar',
	XK = 'Republic of Kosovo',
	RE = 'Réunion',
	RO = 'Romania',
	RU = 'Russian Federation',
	RW = 'Rwanda',
	SH = 'Saint Helena',
	KN = 'Saint Kitts and Nevis',
	LC = 'Saint Lucia',
	PM = 'Saint Pierre and Miquelon',
	VC = 'Saint Vincent and the Grenadines',
	WS = 'Samoa',
	SM = 'San Marino',
	ST = 'Sao Tome and Principe',
	SA = 'Saudi Arabia',
	SN = 'Senegal',
	RS = 'Serbia',
	SC = 'Seychelles',
	SL = 'Sierra Leone',
	SG = 'Singapore',
	SX = 'Sint Maarten (Dutch part)',
	SK = 'Slovakia',
	SI = 'Slovenia',
	SB = 'Solomon Islands',
	SO = 'Somalia',
	ZA = 'South Africa',
	GS = 'South Georgia and the South Sandwich Islands',
	KR = 'South Korea',
	SS = 'South Sudan',
	ES = 'Spain',
	LK = 'Sri Lanka',
	SD = 'Sudan',
	SR = 'Suriname',
	SJ = 'Svalbard and Jan Mayen',
	SZ = 'Swaziland',
	SE = 'Sweden',
	CH = 'Switzerland',
	TW = 'Taiwan, Province of China',
	TJ = 'Tajikistan',
	TZ = 'Tanzania, United Republic of',
	TH = 'Thailand',
	TL = 'Timor-Leste',
	TG = 'Togo',
	TK = 'Tokelau',
	TO = 'Tonga',
	TT = 'Trinidad and Tobago',
	TN = 'Tunisia',
	TM = 'Turkmenistan',
	TC = 'Turks and Caicos Islands',
	TV = 'Tuvalu',
	UG = 'Uganda',
	UA = 'Ukraine',
	AE = 'United Arab Emirates',
	GB = 'United Kingdom',
	US = 'United States',
	UY = 'Uruguay',
	UZ = 'Uzbekistan',
	VE = 'Venezuela',
	VN = 'Vietnam',
	WF = 'Wallis and Futuna',
	EH = 'Western Sahara',
	YE = 'Yemen',
	ZM = 'Zambia',
	ZW = 'Zimbabwe',
}

export type ECountryCode = { [K in keyof typeof ECountryCodeName]?: K };
export const ECountryCode: ECountryCode = Object.freeze(
	Object.keys(ECountryCodeName).reduce((acc, key) => Object.assign({}, acc, { [key]: key }), {}),
);
export type ECountryName = { [K in typeof ECountryCodeName[keyof typeof ECountryCodeName]]?: K };
export const ECountryName: ECountryName = Object.values(ECountryCodeName).reduce(
	(acc, key) => Object.assign({}, acc, { [key]: key }),
	{},
);
export type ECountryCodeToName = { [K: string]: string };
export const ECountryCodeToName: ECountryCodeToName = Object.keys(ECountryCodeName).reduce(
	(acc, key) => Object.assign({}, acc, { [key]: ECountryCodeName[key] }),
	{},
);

export enum EAustraliaStateName {
	'Australian Capital Territory',
	'New South Wales',
	'Northern Territory',
	'Queensland',
	'South Australia',
	'Tasmania',
	'Victoria',
	'Western Australia',
}

export enum EAustraliaStateCode {
	ACT,
	NSW,
	NT,
	QLD,
	SA,
	TAS,
	VIC,
	WA,
}

export enum ECanadaStateName {
	'Alberta',
	'British Columbia',
	'Manitoba',
	'New Brunswick',
	'Newfoundland and Labrador',
	'Northwest Territories',
	'Nova Scotia',
	'Nunavut',
	'Ontario',
	'Prince Edward Island',
	'Quebec',
	'Saskatchewan',
	'Yukon',
}

export enum ECanadaStateCode {
	AB,
	BC,
	MB,
	NB,
	NL,
	NT,
	NS,
	NU,
	ON,
	PE,
	QC,
	SK,
	YT,
}

export const CCountryStateName = Object.freeze({
	Australia: EAustraliaStateName,
	Canada: ECanadaStateName,
});

export const CCountryStateCode = Object.freeze({
	Australia: EAustraliaStateCode,
	Canada: ECanadaStateCode,
});

export type Country = {
	name: ECountryName[keyof ECountryName];
	code: ECountryCode[keyof ECountryCode];
	phoneCode: string;
	states?: {
		name?: ThisType<typeof CCountryStateName[keyof typeof CCountryStateName]>;
		code?: ThisType<typeof CCountryStateCode[keyof typeof CCountryStateCode]>;
	}[];
	postcodeRequired?: boolean;
	groupBy?: string;
};

export const countries: Country[] = [
	{ name: ECountryName['Aland Islands'], code: ECountryCode.AX, phoneCode: '+358' },
	{ name: ECountryName['Albania'], code: ECountryCode.AL, phoneCode: '+355' },
	{ name: ECountryName['Algeria'], code: ECountryCode.DZ, phoneCode: '+213' },
	{ name: ECountryName['American Samoa'], code: ECountryCode.AS, phoneCode: '+1684' },
	{ name: ECountryName['Andorra'], code: ECountryCode.AD, phoneCode: '+376' },
	{ name: ECountryName['Angola'], code: ECountryCode.AO, phoneCode: '+244' },
	{ name: ECountryName['Anguilla'], code: ECountryCode.AI, phoneCode: '+1264' },
	{ name: ECountryName['Antigua and Barbuda'], code: ECountryCode.AG, phoneCode: '+1268' },
	{ name: ECountryName['Argentina'], code: ECountryCode.AR, phoneCode: '+54' },
	{ name: ECountryName['Armenia'], code: ECountryCode.AM, phoneCode: '+374' },
	{ name: ECountryName['Aruba'], code: ECountryCode.AW, phoneCode: '+297' },
	{
		name: ECountryName['Australia'],
		code: ECountryCode.AU,
		phoneCode: '+61',
		states: [
			{
				name: CCountryStateName.Australia['Australian Capital Territory'],
				code: CCountryStateCode.Australia.ACT,
			},
			{ name: CCountryStateName.Australia['New South Wales'], code: CCountryStateCode.Australia.NSW },
			{ name: CCountryStateName.Australia['Northern Territory'], code: CCountryStateCode.Australia.NT },
			{ name: CCountryStateName.Australia['Queensland'], code: CCountryStateCode.Australia.QLD },
			{ name: CCountryStateName.Australia['South Australia'], code: CCountryStateCode.Australia.SA },
			{ name: CCountryStateName.Australia['Tasmania'], code: CCountryStateCode.Australia.TAS },
			{ name: CCountryStateName.Australia['Victoria'], code: CCountryStateCode.Australia.VIC },
			{ name: CCountryStateName.Australia['Western Australia'], code: CCountryStateCode.Australia.WA },
		],
	},
	{ name: ECountryName['Austria'], code: ECountryCode.AT, phoneCode: '+43', postcodeRequired: true },
	{ name: ECountryName['Azerbaijan'], code: ECountryCode.AZ, phoneCode: '+994' },
	{ name: ECountryName['Bahamas'], code: ECountryCode.BS, phoneCode: '+1242' },
	{ name: ECountryName['Bahrain'], code: ECountryCode.BH, phoneCode: '+973' },
	{ name: ECountryName['Bangladesh'], code: ECountryCode.BD, phoneCode: '+880' },
	{ name: ECountryName['Barbados'], code: ECountryCode.BB, phoneCode: '+1246' },
	{ name: ECountryName['Belarus'], code: ECountryCode.BY, phoneCode: '+375' },
	{ name: ECountryName['Belize'], code: ECountryCode.BZ, phoneCode: '+501' },
	{ name: ECountryName['Benin'], code: ECountryCode.BJ, phoneCode: '+229' },
	{ name: ECountryName['Bermuda'], code: ECountryCode.BM, phoneCode: '+1441' },
	{ name: ECountryName['Bhutan'], code: ECountryCode.BT, phoneCode: '+975' },
	{ name: ECountryName['Bolivia'], code: ECountryCode.BO, phoneCode: '+591' },
	{ name: ECountryName['Bosnia and Herzegovina'], code: ECountryCode.BA, phoneCode: '+387' },
	{ name: ECountryName['Bonaire, Sint Eustatius and Saba'], code: ECountryCode.BQ, phoneCode: '+5997' },
	{ name: ECountryName['Botswana'], code: ECountryCode.BW, phoneCode: '+267' },
	{ name: ECountryName['Bouvet Island'], code: ECountryCode.BV, phoneCode: '+47' },
	{ name: ECountryName['Brazil'], code: ECountryCode.BR, phoneCode: '+55' },
	{ name: ECountryName['British Indian Ocean Territory'], code: ECountryCode.IO, phoneCode: '+246' },
	{ name: ECountryName['Virgin Islands (British)'], code: ECountryCode.VG, phoneCode: '+1284' },
	{ name: ECountryName['Brunei Darussalam'], code: ECountryCode.BN, phoneCode: '+673' },
	{ name: ECountryName['Bulgaria'], code: ECountryCode.BG, phoneCode: '+359', postcodeRequired: true },
	{ name: ECountryName['Burkina Faso'], code: ECountryCode.BF, phoneCode: '+226' },
	{ name: ECountryName['Burundi'], code: ECountryCode.BI, phoneCode: '+257' },
	{ name: ECountryName['Cambodia'], code: ECountryCode.KH, phoneCode: '+855' },
	{ name: ECountryName['Cameroon'], code: ECountryCode.CM, phoneCode: '+237' },
	{
		name: ECountryName['Canada'],
		code: ECountryCode.CA,
		phoneCode: '+1',
		postcodeRequired: true,
		states: [
			{ name: CCountryStateName.Canada['Alberta'], code: CCountryStateCode.Canada.AB },
			{ name: CCountryStateName.Canada['British Columbia'], code: CCountryStateCode.Canada.BC },
			{ name: CCountryStateName.Canada['Manitoba'], code: CCountryStateCode.Canada.MB },
			{ name: CCountryStateName.Canada['New Brunswick'], code: CCountryStateCode.Canada.NB },
			{ name: CCountryStateName.Canada['Newfoundland and Labrador'], code: CCountryStateCode.Canada.NL },
			{ name: CCountryStateName.Canada['Northwest Territories'], code: CCountryStateCode.Canada.NT },
			{ name: CCountryStateName.Canada['Nova Scotia'], code: CCountryStateCode.Canada.NS },
			{ name: CCountryStateName.Canada['Nunavut'], code: CCountryStateCode.Canada.NU },
			{ name: CCountryStateName.Canada['Ontario'], code: CCountryStateCode.Canada.ON },
			{ name: CCountryStateName.Canada['Prince Edward Island'], code: CCountryStateCode.Canada.PE },
			{ name: CCountryStateName.Canada['Quebec'], code: CCountryStateCode.Canada.QC },
			{ name: CCountryStateName.Canada['Saskatchewan'], code: CCountryStateCode.Canada.SK },
			{ name: CCountryStateName.Canada['Yukon'], code: CCountryStateCode.Canada.YT },
		],
	},
	{ name: ECountryName['Cabo Verde'], code: ECountryCode.CV, phoneCode: '+238' },
	{ name: ECountryName['Cayman Islands'], code: ECountryCode.KY, phoneCode: '+1345' },
	{ name: ECountryName['Central African Republic'], code: ECountryCode.CF, phoneCode: '+236' },
	{ name: ECountryName['Chad'], code: ECountryCode.TD, phoneCode: '+235' },
	{ name: ECountryName['Chile'], code: ECountryCode.CL, phoneCode: '+56' },
	{ name: ECountryName['China'], code: ECountryCode.CN, phoneCode: '+86' },
	{ name: ECountryName['Christmas Island'], code: ECountryCode.CX, phoneCode: '+61' },
	{ name: ECountryName['Cocos (Keeling) Islands'], code: ECountryCode.CC, phoneCode: '+61' },
	{ name: ECountryName['Colombia'], code: ECountryCode.CO, phoneCode: '+57' },
	{ name: ECountryName['Comoros'], code: ECountryCode.KM, phoneCode: '+269' },
	{ name: ECountryName['Congo'], code: ECountryCode.CG, phoneCode: '+242' },
	{ name: ECountryName['Congo (Democratic Republic of the)'], code: ECountryCode.CD, phoneCode: '+243' },
	{ name: ECountryName['Cook Islands'], code: ECountryCode.CK, phoneCode: '+682' },
	{ name: ECountryName['Costa Rica'], code: ECountryCode.CR, phoneCode: '+506' },
	{ name: ECountryName['Croatia'], code: ECountryCode.HR, phoneCode: '+385', postcodeRequired: true },
	{ name: ECountryName['Cuba'], code: ECountryCode.CU, phoneCode: '+53' },
	{ name: ECountryName['Curaçao'], code: ECountryCode.CW, phoneCode: '+599' },
	{ name: ECountryName['Cyprus'], code: ECountryCode.CY, phoneCode: '+357', postcodeRequired: true },
	{ name: ECountryName['Czech Republic'], code: ECountryCode.CZ, phoneCode: '+420', postcodeRequired: true },
	{ name: ECountryName['Denmark'], code: ECountryCode.DK, phoneCode: '+45', postcodeRequired: true },
	{ name: ECountryName['Djibouti'], code: ECountryCode.DJ, phoneCode: '+253' },
	{ name: ECountryName['Dominica'], code: ECountryCode.DM, phoneCode: '+1767' },
	{ name: ECountryName['Dominican Republic'], code: ECountryCode.DO, phoneCode: '+1809' },
	{ name: ECountryName['Ecuador'], code: ECountryCode.EC, phoneCode: '+593' },
	{ name: ECountryName['Egypt'], code: ECountryCode.EG, phoneCode: '+20' },
	{ name: ECountryName['El Salvador'], code: ECountryCode.SV, phoneCode: '+503' },
	{ name: ECountryName['Equatorial Guinea'], code: ECountryCode.GQ, phoneCode: '+240' },
	{ name: ECountryName['Eritrea'], code: ECountryCode.ER, phoneCode: '+291' },
	{ name: ECountryName['Estonia'], code: ECountryCode.EE, phoneCode: '+372', postcodeRequired: true },
	{ name: ECountryName['Ethiopia'], code: ECountryCode.ET, phoneCode: '+251' },
	{ name: ECountryName['Falkland Islands (Malvinas)'], code: ECountryCode.FK, phoneCode: '+500' },
	{ name: ECountryName['Faroe Islands'], code: ECountryCode.FO, phoneCode: '+298' },
	{ name: ECountryName['Fiji'], code: ECountryCode.FJ, phoneCode: '+679' },
	{ name: ECountryName['Finland'], code: ECountryCode.FI, phoneCode: '+358', postcodeRequired: true },
	{ name: ECountryName['France'], code: ECountryCode.FR, phoneCode: '+33', postcodeRequired: true },
	{ name: ECountryName['French Guiana'], code: ECountryCode.GF, phoneCode: '+594' },
	{ name: ECountryName['French Polynesia'], code: ECountryCode.PF, phoneCode: '+689' },
	{ name: ECountryName['French Southern Territories'], code: ECountryCode.TF, phoneCode: '+33' },
	{ name: ECountryName['Gabon'], code: ECountryCode.GA, phoneCode: '+241' },
	{ name: ECountryName['Gambia'], code: ECountryCode.GM, phoneCode: '+220' },
	{ name: ECountryName['Georgia'], code: ECountryCode.GE, phoneCode: '+995' },
	{ name: ECountryName['Germany'], code: ECountryCode.DE, phoneCode: '+49', postcodeRequired: true },
	{ name: ECountryName['Ghana'], code: ECountryCode.GH, phoneCode: '+233' },
	{ name: ECountryName['Gibraltar'], code: ECountryCode.GI, phoneCode: '+350' },
	{ name: ECountryName['Greece'], code: ECountryCode.GR, phoneCode: '+30', postcodeRequired: true },
	{ name: ECountryName['Greenland'], code: ECountryCode.GL, phoneCode: '+299' },
	{ name: ECountryName['Grenada'], code: ECountryCode.GD, phoneCode: '+1473' },
	{ name: ECountryName['Guadeloupe'], code: ECountryCode.GP, phoneCode: '+590' },
	{ name: ECountryName['Guam'], code: ECountryCode.GU, phoneCode: '+1671' },
	{ name: ECountryName['Guatemala'], code: ECountryCode.GT, phoneCode: '+502' },
	{ name: ECountryName['Guernsey'], code: ECountryCode.GG, phoneCode: '+44' },
	{ name: ECountryName['Guinea'], code: ECountryCode.GN, phoneCode: '+224' },
	{ name: ECountryName['Guinea-Bissau'], code: ECountryCode.GW, phoneCode: '+245' },
	{ name: ECountryName['Guyana'], code: ECountryCode.GY, phoneCode: '+592' },
	{ name: ECountryName['Haiti'], code: ECountryCode.HT, phoneCode: '+509' },
	{ name: ECountryName['Heard Island and McDonald Islands'], code: ECountryCode.HM, phoneCode: '+672' },
	{ name: ECountryName['Holy See'], code: ECountryCode.VA, phoneCode: '+379' },
	{ name: ECountryName['Hong Kong'], code: ECountryCode.HK, phoneCode: '+852' },
	{ name: ECountryName['Honduras'], code: ECountryCode.HN, phoneCode: '+504' },
	{ name: ECountryName['Hungary'], code: ECountryCode.HU, phoneCode: '+36', postcodeRequired: true },
	{ name: ECountryName['Iceland'], code: ECountryCode.IS, phoneCode: '+354' },
	{ name: ECountryName['India'], code: ECountryCode.IN, phoneCode: '+91' },
	{ name: ECountryName['Indonesia'], code: ECountryCode.ID, phoneCode: '+62' },
	{ name: ECountryName["Côte d'Ivoire"], code: ECountryCode.CI, phoneCode: '+225' },
	{ name: ECountryName['Iran'], code: ECountryCode.IR, phoneCode: '+98' },
	{ name: ECountryName['Ireland'], code: ECountryCode.IE, phoneCode: '+353', postcodeRequired: true },
	{ name: ECountryName['Isle of Man'], code: ECountryCode.IM, phoneCode: '+44' },
	{ name: ECountryName['Israel'], code: ECountryCode.IL, phoneCode: '+972' },
	{ name: ECountryName['Italy'], code: ECountryCode.IT, phoneCode: '+39', postcodeRequired: true },
	{ name: ECountryName['Jamaica'], code: ECountryCode.JM, phoneCode: '+1876' },
	{ name: ECountryName['Jersey'], code: ECountryCode.JE, phoneCode: '+44' },
	{ name: ECountryName['Jordan'], code: ECountryCode.JO, phoneCode: '+962' },
	{ name: ECountryName['Kazakhstan'], code: ECountryCode.KZ, phoneCode: '+7' },
	{ name: ECountryName['Kenya'], code: ECountryCode.KE, phoneCode: '+254' },
	{ name: ECountryName['Kiribati'], code: ECountryCode.KI, phoneCode: '+686' },
	{ name: ECountryName['Kuwait'], code: ECountryCode.KW, phoneCode: '+965' },
	{ name: ECountryName['Kyrgyzstan'], code: ECountryCode.KG, phoneCode: '+996' },
	{ name: ECountryName['Latvia'], code: ECountryCode.LV, phoneCode: '+371', postcodeRequired: true },
	{ name: ECountryName['Lebanon'], code: ECountryCode.LB, phoneCode: '+961' },
	{ name: ECountryName['Lesotho'], code: ECountryCode.LS, phoneCode: '+266' },
	{ name: ECountryName['Liberia'], code: ECountryCode.LR, phoneCode: '+231' },
	{ name: ECountryName['Libya'], code: ECountryCode.LY, phoneCode: '+218' },
	{ name: ECountryName['Liechtenstein'], code: ECountryCode.LI, phoneCode: '+423' },
	{ name: ECountryName['Lithuania'], code: ECountryCode.LT, phoneCode: '+370', postcodeRequired: true },
	{ name: ECountryName['Luxembourg'], code: ECountryCode.LU, phoneCode: '+352', postcodeRequired: true },
	{ name: ECountryName['Macao'], code: ECountryCode.MO, phoneCode: '+853' },
	{ name: ECountryName['Macedonia'], code: ECountryCode.MK, phoneCode: '+389' },
	{ name: ECountryName['Madagascar'], code: ECountryCode.MG, phoneCode: '+261' },
	{ name: ECountryName['Malawi'], code: ECountryCode.MW, phoneCode: '+265' },
	{ name: ECountryName['Malaysia'], code: ECountryCode.MY, phoneCode: '+60' },
	{ name: ECountryName['Maldives'], code: ECountryCode.MV, phoneCode: '+960' },
	{ name: ECountryName['Mali'], code: ECountryCode.ML, phoneCode: '+223' },
	{ name: ECountryName['Malta'], code: ECountryCode.MT, phoneCode: '+356', postcodeRequired: true },
	{ name: ECountryName['Marshall Islands'], code: ECountryCode.MH, phoneCode: '+692' },
	{ name: ECountryName['Martinique'], code: ECountryCode.MQ, phoneCode: '+596' },
	{ name: ECountryName['Mauritania'], code: ECountryCode.MR, phoneCode: '+222' },
	{ name: ECountryName['Mauritius'], code: ECountryCode.MU, phoneCode: '+230' },
	{ name: ECountryName['Mayotte'], code: ECountryCode.YT, phoneCode: '+262' },
	{ name: ECountryName['Mexico'], code: ECountryCode.MX, phoneCode: '+52' },
	{ name: ECountryName['Micronesia'], code: ECountryCode.FM, phoneCode: '+691' },
	{ name: ECountryName['Moldova'], code: ECountryCode.MD, phoneCode: '+373' },
	{ name: ECountryName['Monaco'], code: ECountryCode.MC, phoneCode: '+377' },
	{ name: ECountryName['Mongolia'], code: ECountryCode.MN, phoneCode: '+976' },
	{ name: ECountryName['Montenegro'], code: ECountryCode.ME, phoneCode: '+382' },
	{ name: ECountryName['Montserrat'], code: ECountryCode.MS, phoneCode: '+1664' },
	{ name: ECountryName['Morocco'], code: ECountryCode.MA, phoneCode: '+212' },
	{ name: ECountryName['Mozambique'], code: ECountryCode.MZ, phoneCode: '+258' },
	{ name: ECountryName['Myanmar'], code: ECountryCode.MM, phoneCode: '+95' },
	{ name: ECountryName['Namibia'], code: ECountryCode.NA, phoneCode: '+264' },
	{ name: ECountryName['Nauru'], code: ECountryCode.NR, phoneCode: '+674' },
	{ name: ECountryName['Nepal'], code: ECountryCode.NP, phoneCode: '+977' },
	{ name: ECountryName['Netherlands'], code: ECountryCode.NL, phoneCode: '+31', postcodeRequired: true },
	{ name: ECountryName['New Caledonia'], code: ECountryCode.NC, phoneCode: '+687' },
	{ name: ECountryName['New Zealand'], code: ECountryCode.NZ, phoneCode: '+64' },
	{ name: ECountryName['Nicaragua'], code: ECountryCode.NI, phoneCode: '+505' },
	{ name: ECountryName['Niger'], code: ECountryCode.NE, phoneCode: '+227' },
	{ name: ECountryName['Nigeria'], code: ECountryCode.NG, phoneCode: '+234' },
	{ name: ECountryName['Niue'], code: ECountryCode.NU, phoneCode: '+683' },
	{ name: ECountryName['Norfolk Island'], code: ECountryCode.NF, phoneCode: '+672' },
	{ name: ECountryName['North Korea'], code: ECountryCode.KP, phoneCode: '+850' },
	{ name: ECountryName['Northern Mariana Islands'], code: ECountryCode.MP, phoneCode: '+1670' },
	{ name: ECountryName['Norway'], code: ECountryCode.NO, phoneCode: '+47' },
	{ name: ECountryName['Oman'], code: ECountryCode.OM, phoneCode: '+968' },
	{ name: ECountryName['Pakistan'], code: ECountryCode.PK, phoneCode: '+92' },
	{ name: ECountryName['Palau'], code: ECountryCode.PW, phoneCode: '+680' },
	{ name: ECountryName['Palestine, State of'], code: ECountryCode.PS, phoneCode: '+970' },
	{ name: ECountryName['Panama'], code: ECountryCode.PA, phoneCode: '+507' },
	{ name: ECountryName['Papua New Guinea'], code: ECountryCode.PG, phoneCode: '+675' },
	{ name: ECountryName['Paraguay'], code: ECountryCode.PY, phoneCode: '+595' },
	{ name: ECountryName['Peru'], code: ECountryCode.PE, phoneCode: '+51' },
	{ name: ECountryName['Philippines'], code: ECountryCode.PH, phoneCode: '+63' },
	{ name: ECountryName['Pitcairn'], code: ECountryCode.PN, phoneCode: '+64' },
	{ name: ECountryName['Poland'], code: ECountryCode.PL, phoneCode: '+48', postcodeRequired: true },
	{ name: ECountryName['Portugal'], code: ECountryCode.PT, phoneCode: '+351', postcodeRequired: true },
	{ name: ECountryName['Puerto Rico'], code: ECountryCode.PR, phoneCode: '+1787' },
	{ name: ECountryName['Qatar'], code: ECountryCode.QA, phoneCode: '+974' },
	{ name: ECountryName['Republic of Kosovo'], code: ECountryCode.XK, phoneCode: '+383' },
	{ name: ECountryName['Réunion'], code: ECountryCode.RE, phoneCode: '+262' },
	{ name: ECountryName['Romania'], code: ECountryCode.RO, phoneCode: '+40', postcodeRequired: true },
	{ name: ECountryName['Russian Federation'], code: ECountryCode.RU, phoneCode: '+7' },
	{ name: ECountryName['Rwanda'], code: ECountryCode.RW, phoneCode: '+250' },
	{ name: ECountryName['Saint Helena'], code: ECountryCode.SH, phoneCode: '+290' },
	{ name: ECountryName['Saint Kitts and Nevis'], code: ECountryCode.KN, phoneCode: '+1869' },
	{ name: ECountryName['Saint Lucia'], code: ECountryCode.LC, phoneCode: '+1758' },
	{ name: ECountryName['Saint Pierre and Miquelon'], code: ECountryCode.PM, phoneCode: '+508' },
	{ name: ECountryName['Saint Vincent and the Grenadines'], code: ECountryCode.VC, phoneCode: '+1784' },
	{ name: ECountryName['Samoa'], code: ECountryCode.WS, phoneCode: '+685' },
	{ name: ECountryName['San Marino'], code: ECountryCode.SM, phoneCode: '+378' },
	{ name: ECountryName['Sao Tome and Principe'], code: ECountryCode.ST, phoneCode: '+239' },
	{ name: ECountryName['Saudi Arabia'], code: ECountryCode.SA, phoneCode: '+966' },
	{ name: ECountryName['Senegal'], code: ECountryCode.SN, phoneCode: '+221' },
	{ name: ECountryName['Serbia'], code: ECountryCode.RS, phoneCode: '+381' },
	{ name: ECountryName['Seychelles'], code: ECountryCode.SC, phoneCode: '+248' },
	{ name: ECountryName['Sierra Leone'], code: ECountryCode.SL, phoneCode: '+232' },
	{ name: ECountryName['Singapore'], code: ECountryCode.SG, phoneCode: '+65' },
	{ name: ECountryName['Sint Maarten (Dutch part)'], code: ECountryCode.SX, phoneCode: '+1721' },
	{ name: ECountryName['Slovakia'], code: ECountryCode.SK, phoneCode: '+421', postcodeRequired: true },
	{ name: ECountryName['Slovenia'], code: ECountryCode.SI, phoneCode: '+386', postcodeRequired: true },
	{ name: ECountryName['Solomon Islands'], code: ECountryCode.SB, phoneCode: '+677' },
	{ name: ECountryName['Somalia'], code: ECountryCode.SO, phoneCode: '+252' },
	{ name: ECountryName['South Africa'], code: ECountryCode.ZA, phoneCode: '+27' },
	{
		name: ECountryName['South Georgia and the South Sandwich Islands'],
		code: ECountryCode.GS,
		phoneCode: '+500',
	},
	{ name: ECountryName['South Korea'], code: ECountryCode.KR, phoneCode: '+82' },
	{ name: ECountryName['South Sudan'], code: ECountryCode.SS, phoneCode: '+211' },
	{ name: ECountryName['Spain'], code: ECountryCode.ES, phoneCode: '+34', postcodeRequired: true },
	{ name: ECountryName['Sri Lanka'], code: ECountryCode.LK, phoneCode: '+94' },
	{ name: ECountryName['Sudan'], code: ECountryCode.SD, phoneCode: '+249' },
	{ name: ECountryName['Suriname'], code: ECountryCode.SR, phoneCode: '+597' },
	{ name: ECountryName['Svalbard and Jan Mayen'], code: ECountryCode.SJ, phoneCode: '+4779' },
	{ name: ECountryName['Swaziland'], code: ECountryCode.SZ, phoneCode: '+268' },
	{ name: ECountryName['Sweden'], code: ECountryCode.SE, phoneCode: '+46', postcodeRequired: true },
	{ name: ECountryName['Switzerland'], code: ECountryCode.CH, phoneCode: '+41' },
	{ name: ECountryName['Taiwan, Province of China'], code: ECountryCode.TW, phoneCode: '+886' },
	{ name: ECountryName['Tajikistan'], code: ECountryCode.TJ, phoneCode: '+992' },
	{ name: ECountryName['Tanzania, United Republic of'], code: ECountryCode.TZ, phoneCode: '+255' },
	{ name: ECountryName['Thailand'], code: ECountryCode.TH, phoneCode: '+66' },
	{ name: ECountryName['Timor-Leste'], code: ECountryCode.TL, phoneCode: '+670' },
	{ name: ECountryName['Togo'], code: ECountryCode.TG, phoneCode: '+228' },
	{ name: ECountryName['Tokelau'], code: ECountryCode.TK, phoneCode: '+690' },
	{ name: ECountryName['Tonga'], code: ECountryCode.TO, phoneCode: '+676' },
	{ name: ECountryName['Trinidad and Tobago'], code: ECountryCode.TT, phoneCode: '+1868' },
	{ name: ECountryName['Tunisia'], code: ECountryCode.TN, phoneCode: '+216' },
	{ name: ECountryName['Turkmenistan'], code: ECountryCode.TM, phoneCode: '+993' },
	{ name: ECountryName['Turks and Caicos Islands'], code: ECountryCode.TC, phoneCode: '+1649' },
	{ name: ECountryName['Tuvalu'], code: ECountryCode.TV, phoneCode: '+688' },
	{ name: ECountryName['Uganda'], code: ECountryCode.UG, phoneCode: '+256' },
	{ name: ECountryName['Ukraine'], code: ECountryCode.UA, phoneCode: '+380' },
	{ name: ECountryName['United Arab Emirates'], code: ECountryCode.AE, phoneCode: '+971' },
	{ name: ECountryName['United Kingdom'], code: ECountryCode.GB, phoneCode: '+44', postcodeRequired: true },
	{ name: ECountryName['United States'], code: ECountryCode.US, phoneCode: '+1' },
	{ name: ECountryName['Uruguay'], code: ECountryCode.UY, phoneCode: '+598' },
	{ name: ECountryName['Uzbekistan'], code: ECountryCode.UZ, phoneCode: '+998' },
	{ name: ECountryName['Venezuela'], code: ECountryCode.VE, phoneCode: '+58' },
	{ name: ECountryName['Vietnam'], code: ECountryCode.VN, phoneCode: '+84' },
	{ name: ECountryName['Wallis and Futuna'], code: ECountryCode.WF, phoneCode: '+681' },
	{ name: ECountryName['Western Sahara'], code: ECountryCode.EH, phoneCode: '+212' },
	{ name: ECountryName['Yemen'], code: ECountryCode.YE, phoneCode: '+967' },
	{ name: ECountryName['Zambia'], code: ECountryCode.ZM, phoneCode: '+260' },
	{ name: ECountryName['Zimbabwe'], code: ECountryCode.ZW, phoneCode: '+263' },
];
