import i18n from '@i18next';

const t = i18n.getLazyT;

export const cookiesTable = {
  headers: [t('Name'), t('Cookie Type'), t('Life Time'), t('Description')],
  rows: [
    ['CAKEPHP', '1st Party', 'until 2035', 'User Authentication'],
    ['SESS***', '1st Party', '10 days', 'Browser Session Tracking'],
    ['__ar_v4', '1st Party', '6 years', 'AdRoll tracker'],
    ['selectedLang', '1st Party', '1 month', 'Website Preference'],
    ['__cfduid', '1st Party', '1 year', 'Cloudflare User identifier'],
    ['__hssc', '1st Party', '30 minutes', 'Hubspot page tracker'],
    ['__hssrc', '1st Party', '', 'Hubspot tracker changed flag'],
    ['__hstc', '1st Party', '2 years', 'Hubspot main cookie'],
    ['__utma', '1st Party', '2 years', 'Google Analytics'],
    ['__utmz', '1st Party', '6 months', 'Google Analytics'],
    ['_ga', '1st Party', '2 years', 'Google Analytics'],
    ['_gaexp', '1st Party', '3 month', 'Google Analytics Expiry'],
    ['_gid', '1st Party', '1 day', 'Google Analytics unique user'],
    ['_ym_isad', '1st Party', '1 day', 'Yandex metrix'],
    ['_ym_uid', '1st Party', '2 years', 'Yandex unique id'],
    ['intercom-id-****', '1st Party', '9 months', 'Intercom Tracker'],
    ['intercom-lou-****', '1st Party', '9 months', 'Intercom'],
    ['intercom-session-****', '1st Party', '1 week', 'Intercom Session ID'],
    ['formisimo', '1st Party', '1 day', 'Form Analytics'],
    ['APID', '1st Party', '1 year', 'Advertising Tracker'],
    ['AWSELB', '3rd Party', '3 hours', 'Advertising Tracker'],
    ['B', '3rd Party', '1 year', 'Social Tracker - Yahoo'],
    ['PugT', '3rd Party', '1 month', 'Advertising Tracker'],
    ['CMDD', '3rd Party', '1 day', 'Advertising Tracker'],
    ['CMID', '3rd Party', '1 year', 'Advertising Tracker'],
    ['CMPRO', '3rd Party', '3 months', 'Advertising Tracker'],
    ['CMPS', '3rd Party', '3 months', 'Advertising Tracker'],
    ['CMRUM3', '3rd Party', '1 year', 'Advertising Tracker'],
    ['CMSC', '3rd Party', '', 'Advertising Tracker'],
    ['CMST', '3rd Party', '1 day', 'Advertising Tracker'],
    ['DOMSYNC', '3rd Party', '1 year', 'Advertising Tracker'],
    ['IDSYNC', '3rd Party', '1 year', 'Advertising Tracker'],
    ['KADUSERCOOKIE', '3rd Party', '3 months', 'Advertising Tracker'],
    ['KRTBCOOKIE_97', '3rd Party', '1 month', 'Advertising Tracker'],
    ['PUBMDCID', '3rd Party', '3 months', 'Advertising Tracker'],
    ['SyncRTB2', '3rd Party', '3 months', 'Advertising Tracker'],
    ['__adroll', '3rd Party', '1 year', 'Advertising Tracker'],
    ['_ofcap_DOC1', '3rd Party', '2 days', 'Advertising Tracker'],
    ['adrl', '3rd Party', '3 months', 'Advertising Tracker'],
    ['anj', '3rd Party', '3 months', 'Advertising Tracker'],
    ['apnxs', '3rd Party', '3 months', 'Advertising Tracker'],
    ['c', '3rd Party', '1 year', 'Advertising Tracker'],
    ['c_user', '3rd Party', '3 months', 'Social Tracker - Facebook'],
    ['criteo', '3rd Party', '1 month', 'Advertising Tracker'],
    ['datr', '3rd Party', '2 years', 'Social Tracker - Facebook'],
    ['f5_cspm', '3rd Party', '', 'Advertising Tracker'],
    ['fr', '3rd Party', '3 months', 'Social Tracker - Facebook'],
    ['i', '3rd Party', '10 years', 'Advertising Tracker'],
    ['i', '3rd Party', '1 year', 'Advertising Tracker'],
    ['icu', '3rd Party', '3 months', 'Advertising Tracker'],
    ['khaos', '3rd Party', '1 year', 'Advertising Tracker'],
    ['mdfrc', '3rd Party', '3 months', 'Advertising Tracker'],
    ['obuid', '3rd Party', '3 months', 'Advertising Tracker'],
    ['p_synced', '3rd Party', '10 days', 'Advertising Tracker'],
    ['pd', '3rd Party', '2 weeks', 'Advertising Tracker'],
    ['pl', '3rd Party', '3 months', 'Social Tracker - Facebook'],
    ['put_1185', '3rd Party', '2 months', 'Advertising Tracker'],
    ['pxrc', '3rd Party', '2 months', 'Advertising Tracker'],
    ['rcktfl', '3rd Party', '3 months', 'Advertising Tracker'],
    ['rlas3', '3rd Party', '6 months', 'Advertising Tracker'],
    ['rpb', '3rd Party', '1 month', 'Advertising Tracker'],
    ['rpx', '3rd Party', '1 month', 'Advertising Tracker'],
    ['rtn1-z', '3rd Party', '6 months', 'Advertising Tracker'],
    ['sb', '3rd Party', '2 years', 'Social Tracker - Facebook'],
    ['sess', '3rd Party', '1 day', 'Advertising Tracker'],
    ['t_gid', '3rd Party', '1 year', 'Advertising Tracker'],
    ['taboola_usg', '3rd Party', '1 year', 'Advertising Tracker'],
    ['tluid', '3rd Party', '3 months', 'Advertising Tracker'],
    ['tuuid', '3rd Party', '1 year', 'Advertising Tracker'],
    ['tuuid_lu', '3rd Party', '1 week', 'Advertising Tracker'],
    ['uuid2', '3rd Party', '3 months', 'Advertising Tracker'],
    ['wd', '3rd Party', '1 week', 'Social Tracker - Facebook'],
    ['xs', '3rd Party', '3 months', 'Social Tracker - Facebook'],
    ['yabs-sid', '3rd Party', '', 'Advertising Tracker'],
    ['yandexuid', '3rd Party', '10 years', 'Advertising Tracker'],
    ['yp', '3rd Party', '10 years', 'Advertising Tracker'],
  ],
  colsPctSize: [30, 20, 20, 30],
};
