version: '3'
services:
  # Minimal Ubuntu 18.04.2 LTS with angular, nodejs, nginx and mongo tools
  wl:
    build: ./
    container_name: wl
    ports:
      - 3000:4201
    volumes:
      - ./server:/app/server
      - ./pm2_services.json:/app/server/dist/pm2_services.json
      - ./logs:/app/logs
    restart: always
    tty: true
  # mongo DB official image based on Minimal Ubuntu 16.04.5 LTS
  redis:
      image: redis
      container_name: redis
      ports:
          - 6379:6379
      restart: always
      tty: true
