export enum EPagePath {
  Home = '',
  About = '/about',
  Products = '/range-of-markets',
  Platform = '/platform',
  Contacts = '/contacts',
  Partnerships = '/partnerships',
  Leverage = '/leverage',
  Login = '/login',
  Logout = '/logout',
  ForgotPassword = '/forgot-password',
  ResetPassword = '/reset-password',
  Registration = '/registration',
  Dashboard = '/dashboard',
  Deposit = '/deposit',
  DepositSuccess = '/deposit/success',
  DepositFailure = '/deposit/failure',
  Withdrawal = '/withdrawal',
  InternalTransfer = '/transfers',
  TransactionStatement = '/statement',
  OpenLiveAccount = '/open-account/live',
  OpenDemoAccount = '/open-account/demo',
  PlatformDownload = '/download',
  Profile = '/profile',
  Verification = '/verification',
  InviteFriends = '/invite-friends',
  NotFound = '/404',
}
